import "./globals.css";
import { GuestListProvider } from "./guest-list/GuestListProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GuestListProvider>
        <body>{children}</body>
      </GuestListProvider>
    </html>
  );
}
