import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { GuestListProvider } from "./guest-list/GuestListProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <GuestListProvider>
          <body>{children}</body>
        </GuestListProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
